Repository itsektionen/songlist, pull requests merged in 2025-07, with the labels that each got.

#48 Fix correct escaping of characters in XML strings
  dist/songs-no-ids.xml
  dist/songs.xml
  src/util/xml.ts
Labels: bug

#53 Add a closest match for failing tests
  package.json
  test/songFiles.test.ts
  yarn.lock
Labels: enhancement

#52 Add alternative song titles
  README.md
  dist/songs.json
  dist/songs.xml
  songs/149_Du_gamla_du_fria.md
  songs/17_Bort_allt_vad_oro_gor.md
  songs/2_Porthos_visa.md
  songs/5_Fredmans_sang_nr_21.md
  songs/65_Masen.md
  src/definitions/song.ts
  src/scripts/create.ts
  src/util/songs.ts
  test/songFiles.test.ts
Labels: enhancement, update songs
